### PR TITLE
PIM447 should work correctly now if SDA is connected to P17/D2 and SCL to P20/D3.

### PR DESCRIPTION
**Pull request by cdc-mkb**
Hello @grasegger 

As of my understanding the SDA and SCL signals are available on pins
17 (D2) and 20 (D3) respectively on Nice!Nano [1].  The pins 6 (D1)
and 8 (D0) are for UART [2].  As you can see on [1], the I2C pins are
already configured correctly on ZMK for this board, so you don't have
to redefine them.

Also I think the devicetree node trackball_pim447@a should belong to
the shield devicetree fragment, not to the board devicetree one.

[1] https://github.com/zmkfirmware/zmk/blob/main/app/boards/arm/nice_nano/nice_nano.dtsi#L45
[2] https://github.com/zmkfirmware/zmk/blob/main/app/boards/arm/nice_nano/nice_nano.dtsi#L51

### CODE REVIEW

**Comment by cdc-mkb** [comment]
Note: I'm not able to test this pull request since I don't own a Nice!Nano board.

**Comment by grasegger** [comment]
@cdc-mkb Thanks, gonna try this :)

**Comment by genkobar** [comment]
Hi @grasegger! Did you have any luck with this?

I'm trying out the firmware on a split handwired keyboard I'm working on. I haven't connected any keys yet, just testing out the pimoroni trackball with the nice nano v2.

**Comment by grasegger** [comment]
@genkobar Sadly no - my direct wiring did not work, and I am not sure why. I am trying again with a board that is wired up correctly from the beginning. I don't give up yet though! :D

**Comment by genkobar** [comment]
@grasegger I've also not had any success getting it to work with a nnv2, but I just recently flushed out a reliable zmk config :)

**Pull request merged**
